#!/bin/bash

TARB_ARCHIVE=$(pwd)/tarballs

echo "Tarball Path: ${TARB_ARCHIVE}"

if [ ! -d "tarballs" ]; then
	mkdir "tarballs"
fi

if [ $# -eq 0 ]; then
	PACKAGE_LIST=$(find . -maxdepth 1 -type d \! -name .)
elif [ $# -eq 1 ]; then
	PACKAGE_LIST=${1}
fi

for ITEM in $(echo $PACKAGE_LIST); do
	if [ -d $ITEM ]; then
		#rm ${TARB_ARCHIVE}/${ITEM}*
		cd ${ITEM}
		pwd
		if [ -f "PKGBUILD" ]; then
			echo "PKGBUILD found."
			makepkg --source || return 1
			mv *.src.tar.gz ${TARB_ARCHIVE}
		fi
		cd ../
	fi
done

